name: release-ali

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Set Environment Variables
        run: |
          echo "VERSION=$(git describe --tags --first-parent --abbrev=7 --long --dirty --always | sed -e 's/^v//g')" >> $GITHUB_ENV
          echo "GOFLAGS='-ldflags=-w -s \"-X=github.com/AI-Horizons-Collective/ollama/version.Version=\$VERSION\" \"-X=github.com/ollama/ollama/server.mode=release\"'" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: registry.cn-wulanchabu.aliyuncs.com/ai-horizons-collective/ollama:latest
          build-args: |
            GOFLAGS=${{ env.GOFLAGS }}
          platforms: linux/amd64
